notifications:
  email:
    recipients:
      - jstobbe@fias.uni-frankfurt.de
    on_success change
    on_failure change

language: cpp
sudo: true

#env:
#  global:
#    matrix:
#      - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
   apt:
     packages:
       - valgrind
       - cmake
       - g++-6
       - gcc-6
       - libboost-all-dev
     sources: &sources
       - boost-latest
       - llvm-toolchain-precise
       - ubuntu-toolchain-r-test


matrix:
#  exclude:
#    env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: linux
      dist: trusty
      env: COMPILER=g++-6
      compiler: g++


script:
  # Combine global build options with OS/compiler-dependent options
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest

after_failure:
  less /home/travis/build/Atomtomate/sys_risk/build/external/trng-prefix/src/trng-stamp/trng-build-*.log


#after_success:
#    - codecov -t c376990f-2ad6-4f7b-bbdb-5378a52e295c -X gcov

