#notifications:
#  email:
#    recipients:
#      - jstobbe@fias.uni-frankfurt.de
#    on_success change
#    on_failure change

language: c++
sudo: true

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -std=c++17 -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - valgrind
            - python-yaml
            - lcov
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
            - valgrind
            - python-yaml
            - lcov
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-7.3 && CXX=g++-7.3"

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - cmake
            - clang-6.0
            - valgrind
            - python-yaml
            - lcov
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"


#- sudo apt-get install -y r-cran-rinside libsundials-dev
before_script:
    - echo "deb https://ftp.fau.de/cran/bin/linux/ubuntu artful/" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y mercurial libeigen3-dev libboost-all-dev libgtest-dev google-mock git libblas-dev liblapack-dev

before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ..
     - make
     - ctest


#after_success:
#    - codecov -t c376990f-2ad6-4f7b-bbdb-5378a52e295c -X gcov

