#notifications:
#  email:
#    recipients:
#      - jstobbe@fias.uni-frankfurt.de
#    on_success change
#    on_failure change

language: generic
sudo: true

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/external
addons:
   apt:
     update: true
     sources:
       - - llvm-toolchain-precise
       - ubuntu-toolchain-r-test
     packages:
       - cmake
       - g++-6
       - gcc-6
    # Global build options and C++ flags
    #- CXX_FLAGS="-Wall -std=c++14 -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    #- RUN_TESTS=true
    #- COVERAGE=false

#matrix:
#  include:
#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          update: true
#          sources: &sources
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-6.0
#          packages:
#            - cmake
#            - g++-4.9
#      env:
#        - MATRIX_EVAL="export CC=gcc-4.9 && CXX=g++-4.9"

#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          update: true
#          sources: &sources
#            - ubuntu-toolchain-r-test
#          packages:
#            - cmake
#            - g++-5
#      env:
#        - MATRIX_EVAL="export CC=gcc-5 && CXX=g++-5"

#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          update: true
#          sources: &sources
#            - ubuntu-toolchain-r-test
#          packages:
#            - cmake
#            - g++-6
#            - valgrind
#            - python-yaml
#            - lcov
#            - libopencv-dev
#      env:
#        - MATRIX_EVAL="export CC=gcc-6 && CXX=g++-6"
#
#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          update: true
#          sources: &sources
#            - ubuntu-toolchain-r-test
#          packages:
#            - cmake
#            - g++-7
#      env:
#        - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7"

#    - os: linux
#      dist: trusty
#      compiler: clang
#      addons:
#        apt:
#          update: true
#          sources:  &sources
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-6.0
#          packages:
#            - cmake
#            - clang-6.0
#      env:
#        - MATRIX_EVAL="export CC=clang-6 && CXX=clang++-6"


#- sudo apt-get install -y r-cran-rinside libsundials-dev
before_script:
    - echo "deb https://ftp.fau.de/cran/bin/linux/ubuntu artful/" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential autotools-dev mercurial libboost-all-dev libgtest-dev google-mock git libblas-dev liblapack-dev
    #libeigen3-dev
#sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc && sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++ &&
before_install:
    - eval "${MATRIX_EVAL}"
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi


script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ..
     - make
     - ctest

after_failure:
  less /home/travis/build/Atomtomate/sys_risk/build/external/trng-prefix/src/trng-stamp/trng-build-*.log


#after_success:
#    - codecov -t c376990f-2ad6-4f7b-bbdb-5378a52e295c -X gcov

